### ISSUE TITLE
Errors returned from plugin are never surfaced to host

### ISSUE THREAD

**Issue by cchamplin** [knqyf263/go-plugin#15]
When a plugin function returns an error, it seems like that error never makes it's way back to the host.

Version: [f7d9444](https://github.com/knqyf263/go-plugin/commit/f7d94447ee0de525262d52bdc51d75e8fdc2fab6)
Reproducible Test: https://github.com/cchamplin/plugin-bug

Host
```go
	_, err = myPlugin.PassDataError(context.Background(), plugin.PassDataRequest{})
	if err == nil {
		t.Error("expected error")
		return
	}
```

Plugin
```go
func (p TestPlugin) PassDataError(ctx context.Context, request host.PassDataRequest) (result host.PassDataReply, err error) {
	return host.PassDataReply{}, fmt.Errorf("an error from the plugin")
}
```

Expected: Test to pass
Actual:
```text
=== RUN   TestPlugin_Error
    plugin_test.go:184: expected error
--- FAIL: TestPlugin_Error (0.10s)

FAIL
```

**Comment by mathetake** [comment]
yeah this is indeed not intuitive and there should be a way to surface errors to the host.
The issue is that the currently generated guest codes just suppress the errors returned by the interface 

- gen: https://github.com/knqyf263/go-plugin/blob/main/gen/plugin.go#L65-L70
- ex: https://github.com/knqyf263/go-plugin/blob/main/tests/well-known/proto/known_plugin.pb.go#L37-L40

we could return the errors string, but not sure whether that's the right way to go if we want to add support for multiple languages.

@knqyf263 @codefromthecrypt @anuraaga thoughts?

**Comment by mathetake** [comment]
possible solution would be like this
```patch
diff --git a/examples/host-functions/greeting/greet_plugin.pb.go b/examples/host-functions/greeting/greet_plugin.pb.go
index d20d5a3..381681c 100644
--- a/examples/host-functions/greeting/greet_plugin.pb.go
+++ b/examples/host-functions/greeting/greet_plugin.pb.go
@@ -36,7 +36,11 @@ func _greeter_greet(ptr, size uint32) uint64 {
        }
        response, err := greeter.Greet(context.Background(), req)
        if err != nil {
-               return 0
+               ptr, size = wasm.ByteToPtr(err.Error())
+               return (uint64(ptr) << uint64(32)) | uint64(size) |
+                       // Indicate that this is the error string by setting the 32-th bit, assuming that
+                       // no data exceeds 31-bit size (2 GiB).
+                       (1 << 31)
        }
 
        b, err = response.MarshalVT()
```

**Comment by anuraaga** [comment]
As a reference, from what I understand wapc calls a host function to pass the error from the guest

https://github.com/wapc/wapc-go/blob/master/engines/wazero/wazero.go#L315

I don't think I've ever found a more portable way to return a string from the guest since trying to return a pointer could still result in that being collected before the host gets a chance to read it, with TinyGo's current GC implementation it's not an issue though.

**Comment by inliquid** [comment]
Are there any plans on fixing this issue anytime soon? The library looks very promising, but atm it requires to use panics on wasm side instead of errors, since errors are lost on their way back to host.

**Comment by codefromthecrypt** [comment]
@inliquid this is a volunteer project, so what you see is what you get. that said, nags are helpful sometimes for the same reason ;)

@dmvolod you are the most active maintainer of this project. What do you think about Takeshi's proposal which is to return a uint64 with the offset/len of an error string, where empty err vs no error is decided by the high bit?

**Comment by dmvolod** [comment]
@codefromthecrypt it's a good option to decide error message by the high bit, working on solution.

Also as alternative option, we could probably always attach serialized [Status](https://jbrandhorst.com/post/grpc-errors/) struct from the standard `google/rpc/status.proto` package to any message, split and analyze it after invocation. Will try to research this approach later.

**Comment by inliquid** [comment]
I just tried latest code from the repo (`v0.5.1-0.20230304000230-1a95073513ee`) and seems that problem persists:
I.e. this still results with nil error from the host point:
```go
func (m MyPlugin) Cat(ctx context.Context, req api.CatReq) (api.CatResp, error) {
	// panic("just panic")
	return api.CatResp{}, errors.New("just error")
}
```

**Comment by dmvolod** [comment]
Hello, @inliquid 

It's very strange. Did you regenerate your plugin code with latest `protoc-gen-go-plugin` binary build form source code as it's not released yet?

**Comment by inliquid** [comment]
@dmvolod I missed that step with stubs regeneration with updated plugin, now everything works as expected, thank you!
